### PR TITLE
fix typescript error

### PR DESCRIPTION
**Pull request by phapdinh**
Hi @wcandillon, I keep noticing this error whenever I was using MediaQuery

react-native-responsive-ui

It gave this warning `JSX element type '{}' is not a constructor function for JSX elements.
  Type '{}' is missing the following properties from type 'Element': type, props, keyts(2605)`

I figured out that this is due to typescript assuming that a functional component will return a react constructor, but that is not the case with MediaQuery because it can sometimes return null or sometimes return string or sometimes returns a number depending on what is passed as a children prop to the MediaQuery. So I set children equal to any because children doesn't always have to be a ReactNode, but can also be a string that you conditionally show if you choose to pass a string in as children. My test for MediaQuery shows an example where it is a string being passed a children versus a ReactNode

### CODE REVIEW

**Comment by wcandillon** [comment]
@phapdinh I agree that this is not the right type. But could use something else than any?

**Comment by phapdinh** [comment]
not that I know of

**Comment by phapdinh** [comment]
you can also set the return type to any and it will fix the error

**Comment by phapdinh** [comment]
However, there is no typescript warning when you pass in string as children or number as children so the typing of ReactNode for children doesn't seem to be doing it's job

**Comment by phapdinh** [comment]
@wcandillon after some research at https://gist.github.com/sebmarkbage/fcb1b6ab493b0c77d589#react-nodes, I converted it back to saying ReactNode for type and set the return value as any to tell typescript that the return type is not necessarily a react constructor to get rid of the error

**Comment by wcandillon** [comment]
It looks like this any type could be `React.ReactNode | null | undefined`. Should children be mandatory actually? What do you think?

**Comment by phapdinh** [comment]
@wcandillon yes I think that children should be mandatory since if you leave it empty then the MediaQuery will crash

**Comment by phapdinh** [comment]
I tried setting the return type to `React.ReactNode | null `, but it didn't clear the error and I can't use this library until the error is cleared because my CI/CD will invalidate the library

**Comment by wcandillon** [comment]
I've made the change, let's see if it passes the CI. Do you agree with this change?

**Comment by wcandillon** [comment]
null is included in React.ReactNode no?

**Comment by phapdinh** [comment]
I think that it is good for now. The function should only return a ReactNode and there is an open issue that needs to be fixed by microsoft here https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20544 and here https://github.com/microsoft/TypeScript/issues/21699 that should allow a functional component to return a ReactNode, but this is a improvement

**Pull request merged**
