### PR TITLE
Move dependencies

### LINKED ISSUE #16: Failed to build DependencyGraph: @providesModule naming collision
Hi,
After adding this dependency, I get:
Bundling `index.android.js`
  Analysing...Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: <path>/node_modules/react-native-responsive-ui/node_modules/react-native/package.json collides with<path>/node_modules/react-native/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: <path>/node_modules/react-native-responsive-ui/node_modules/react-native/package.json collides with <path>/node_modules/react-native/package.json

I don't really know what this means, and googling for that made me more confused than expected.
I don't know if that's relevant, I'm using react-native 0.42 (0.43+ only cause dependency conflicts because modules won't use an alpha version of react).

### PR DESCRIPTION
**Pull request by wcandillon**
fixes #16, #10

### CODE REVIEW

**Comment by piranna** [comment]
Test is failing... :-/

```js
node node_modules/jest/bin/jest.js
 FAIL  ./App.test.js
  ● Test suite failed to run

    Cannot find module 'react-native/packager/src/Resolver/polyfills/babelHelpers.js' from 'setup.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/jest-expo/src/setup.js:5:9)
```

**Comment by piranna** [comment]
Can this be published on `npm` registry?

**Comment by wcandillon** [comment]
@piranna yes working on it. I think that it didn't published because I had an emoji in the semantic commit message 😅

**Comment by piranna** [comment]
> I think that it didn't published because I had an emoji in the semantic commit message

Lol X-D Just before publishing I do `npm version <whatever>` to upgrade the version number, and it also do a commit just for that version upgrade and creates a tag for it, that later becames a release on Github. Very convenient command :-)

**Comment by piranna** [comment]
In this case, you could do `npm version patch` or `npm version minor`.

**Comment by wcandillon** [comment]
`1.1.1` is published. I use `semantic-release` for publishing the package.

**Comment by piranna** [comment]
> I use semantic-release for publishing the package.

Good idea :-) Thanks! :-D

**Comment by wemakeweb** [comment]
Please publish

**Pull request merged**
